### ISSUE TITLE
how to connect a remote host frida server?

### ISSUE THREAD

**Issue by gMan1990** [5alt/hrida#1]

**Comment by gMan1990** [comment]
https://github.com/frida/frida/issues/70#issuecomment-522453301

**Comment by agentanonymus** [comment]
Como usar o Frida via depuração Wi-Fi:

Existe uma maneira simples de usar o acesso remoto via depuração Wi-Fi.

Primeiro, ative a depuração Wi-Fi:

Clique em cima e pegue o IP e a porta de acesso.
No terminal ou CMD do seu PC, execute o comando:
Copy
adb connect <endereço_IP_do_seu_dispositivo>:45844
Lembrete: O PC e o celular devem estar conectados na mesma rede Wi-Fi.

Depois de executar o comando no terminal ou CMD do seu PC, você verá uma mensagem de conexão.

Em seguida, conecte-se ao servidor do Frida da seguinte forma:

Copy
./frida-server -l <endereço_IP_do_seu_dispositivo>

**Comment by agentanonymus** [comment]
How to use Frida via Wi-Fi purification:

There is a simple way to use remote access via Wi-Fi purification.

First, activate the Wi-Fi purification:

Clique at the top and bottom or IP and at the door of access.
No terminal or CMD from your PC, execute or command:
Copy
adb connect <endereço_IP_do_seu_disposizione>:45844
Please note: Your PC and mobile phone must be connected via Wi-Fi.

After executing the command in terminal or CMD on your PC, you will see a connection message.

Below, connect to Frida's servant in the following way:

Copy
./frida-server -l 192.168.0.0
